import type { Feature, ThemeKey } from '../types';

export const themes: { key: ThemeKey; title: string; intro: string }[] = [
  { key: 'start', title: 'Start', intro: 'A calm place to begin every day of your search.' },
  { key: 'find', title: 'Find', intro: 'Bring the right offers to you instead of checking every site.' },
  { key: 'track', title: 'Track', intro: 'One list of applications, four ways to look at it.' },
  { key: 'prepare', title: 'Prepare', intro: 'Walk into every interview with what you need.' },
  { key: 'profile', title: 'Profile', intro: 'Your career story, entered once and reused everywhere.' },
  { key: 'control', title: 'Control', intro: 'Settings that put you in charge of your data.' },
];

export const features: Feature[] = [
  {
    key: 'home-overview',
    theme: 'start',
    title: 'Home',
    summary: 'A start page that shows what matters today: your next interview, your applications at a glance and your resume.',
    bullets: ['Next interview in one card', 'Applications grouped by status', 'Your current resume within reach'],
    icon: 'home',
    plan: 'free',
    screenshotAlt: 'The applyspace Home page with the next interview, application counts and the current resume',
    order: 10,
  },
  {
    key: 'offers-search',
    theme: 'find',
    title: 'Job offers search',
    summary: 'See the offers that match your search profiles in one list, with where each offer comes from.',
    bullets: ['One list instead of many tabs', 'An offer published in several places shows up once', 'Save an offer you like as an application'],
    icon: 'search',
    plan: 'free',
    screenshotAlt: 'A list of job offers with company, title, location and source job boards',
    order: 20,
  },
  {
    key: 'search-profiles',
    theme: 'find',
    title: 'Search profiles',
    summary: 'Describe what you look for once: job titles, places anywhere in the world, contracts, salary, sectors and company size.',
    bullets: ['Several job titles in one profile', 'Remote, on-site or hybrid', 'More search profiles on Plus and Max'],
    icon: 'filter',
    plan: 'free',
    screenshotAlt: 'The search profile form with job titles, locations, contract types and salary range',
    order: 30,
  },
  {
    key: 'applications-board',
    theme: 'track',
    title: 'Board',
    summary: 'Columns by status: waiting for an answer, interviewing, accepted, rejected, ghosted and withdrawn.',
    bullets: ['Move a card or change its status from a menu', 'See at a glance what needs a follow-up', 'Company logos make cards easy to scan'],
    icon: 'board',
    plan: 'free',
    screenshotAlt: 'The applications board with one column per status and application cards',
    order: 40,
  },
  {
    key: 'applications-table',
    theme: 'track',
    title: 'Table',
    summary: 'Every application in a sortable table when you want to compare, filter and clean up.',
    bullets: ['Sort by any column', 'Choose which columns to show', 'Open any row for the details'],
    icon: 'table',
    plan: 'free',
    screenshotAlt: 'The applications table with company, title, status, applied date and location columns',
    order: 50,
  },
  {
    key: 'applications-timeline',
    theme: 'track',
    title: 'Timeline',
    summary: 'See when you applied, when companies replied and when interviews and deadlines fall.',
    bullets: ['One row per application', 'Interviews and deadlines as markers', 'A line for today'],
    icon: 'timeline',
    plan: 'free',
    screenshotAlt: 'The applications timeline with markers for applied dates, interviews and deadlines',
    order: 60,
  },
  {
    key: 'applications-map',
    theme: 'track',
    title: 'Map',
    summary: 'Your applications on a map, grouped by city. Remote applications are listed apart, never dropped.',
    bullets: ['Pins with a count per city', 'Select a pin to list its applications', 'Useful when you are open to relocating'],
    icon: 'map',
    plan: 'free',
    screenshotAlt: 'A map with pins for the cities of your applications',
    order: 70,
  },
  {
    key: 'application-limits',
    theme: 'track',
    title: 'Room for your applications',
    summary: 'Each plan comes with its own room for applications, shown next to the hub title. The Pricing page compares them.',
    bullets: ['A counter next to the hub title', 'The same limit is enforced by the database', 'Upgrade only when you need the room'],
    icon: 'check',
    plan: 'free',
    screenshotAlt: 'The applications hub header showing the used and available application count',
    order: 80,
  },
  {
    key: 'interview-tracking',
    theme: 'prepare',
    title: 'Interview tracking',
    summary: 'Keep every interview with its application: date, step and notes. Upcoming interviews show on Home.',
    bullets: ['One space for dates and notes', 'Upcoming interviews at a glance', 'Interview templates to reuse'],
    icon: 'interview',
    plan: 'free',
    screenshotAlt: 'The interviews page listing upcoming interviews with their dates and companies',
    order: 90,
  },
  {
    key: 'fit-messages',
    theme: 'prepare',
    title: 'Cover letters and fit messages',
    summary: 'Write with your own AI account (Claude, OpenAI or Gemini) and edit as much as you like.',
    bullets: ['One letter or message per application', 'Edit without limit', 'You stay in control of the final text'],
    icon: 'message',
    plan: 'free',
    screenshotAlt: 'A text editor with a cover letter next to the job offer',
    order: 100,
  },
  {
    key: 'profile-resume-parser',
    theme: 'profile',
    title: 'Profile and resume parser',
    summary: 'Import a PDF or DOCX resume and applyspace extracts your experiences, education, skills and languages for you to review.',
    bullets: ['PDF and DOCX, up to 3 MB', 'Nothing is saved until you confirm', 'Re-import later without creating duplicates'],
    icon: 'file',
    plan: 'free',
    screenshotAlt: 'The profile page with experiences and skills filled from an imported resume',
    order: 110,
  },
  {
    key: 'writing-style',
    theme: 'profile',
    title: 'Writing style',
    summary: 'Tell applyspace how you write so letters and messages sound like you.',
    bullets: ['Your tone, your vocabulary', 'Used for every letter and message', 'Change it whenever you want'],
    icon: 'pen',
    plan: 'free',
    screenshotAlt: 'The writing style section of the profile',
    order: 120,
  },
  {
    key: 'settings',
    theme: 'control',
    title: 'Settings',
    summary: 'General, account, privacy, billing, profile and connectors, in English or French.',
    bullets: ['Choose your language', 'Manage your plan', 'Connect the accounts you want to use'],
    icon: 'settings',
    plan: 'free',
    screenshotAlt: 'The settings window with sections for general, account, privacy, billing, profile and connectors',
    order: 130,
  },
  {
    key: 'privacy',
    theme: 'control',
    title: 'Privacy by design',
    summary: 'Your account and data are stored in the cloud with per-user access rules, and product analytics are opt-in.',
    bullets: ['Data stored in the cloud, scoped to your account', 'Analytics only after you agree', 'You decide what to import'],
    icon: 'lock',
    plan: 'free',
    screenshotAlt: 'The privacy section of the settings',
    order: 140,
  },
];
