import type { Feature, ThemeKey } from '../types';

export const themes: { key: ThemeKey; title: string; intro: string }[] = [
  { key: 'track', title: 'Find and track', intro: 'From the offer to the answer, in one list.' },
  { key: 'prepare', title: 'Prepare and apply', intro: 'Your profile, your interviews and your words.' },
  { key: 'everywhere', title: 'Wherever you work', intro: 'One account on your Mac, in your browser and on your phone.' },
  { key: 'control', title: 'Your accounts, your data', intro: 'Connect what helps, and stay in control of the rest.' },
];

/**
 * Every feature on the roadmap. `soon: true` marks what is not in the product yet (shown with a "Soon" tag):
 * flip it when a feature ships. Keep the copy short, with no job board names, prices or plan limits.
 */
export const features: Feature[] = [
  {
    key: 'offers-search',
    theme: 'track',
    title: 'Job offers search',
    summary: 'Searches run from the desktop app with your own job board sessions. Results are saved to your account.',
    bullets: ['Filters by title, place, contract and remote', 'Saved offers', 'Alerts for new offers'],
    icon: 'search',
    plan: 'free',
    soon: true,
    order: 10,
  },
  {
    key: 'applications-hub',
    theme: 'track',
    title: 'Applications hub',
    summary: 'Every application in one place, with its status, from first contact to the final answer.',
    bullets: ['Board, Table, Timeline and Map views', 'Create applications by hand', 'Statuses that follow your progress'],
    icon: 'board',
    plan: 'free',
    order: 20,
  },
  {
    key: 'home-overview',
    theme: 'track',
    title: 'Home overview',
    summary: 'A start page with what matters today: your next interview, your applications at a glance and your resume.',
    bullets: ['Next interview in one card', 'Applications by status', 'Your resume within reach'],
    icon: 'home',
    plan: 'free',
    order: 30,
  },
  {
    key: 'profile-import',
    theme: 'prepare',
    title: 'Profile from your resume',
    summary: 'Import your resume or your LinkedIn export. Parsing fills your profile for you to review.',
    bullets: ['PDF or DOCX resume', 'LinkedIn PDF export', 'Nothing saved until you confirm'],
    icon: 'upload',
    plan: 'free',
    order: 40,
  },
  {
    key: 'interview-tracking',
    theme: 'prepare',
    title: 'Interview tracking',
    summary: 'Every interview linked to its application, round by round.',
    bullets: ['Rounds and dates', 'Prep notes and checklists', 'Questions to ask'],
    icon: 'interview',
    plan: 'free',
    order: 50,
  },
  {
    key: 'writing-assistant',
    theme: 'prepare',
    title: 'AI writing assistant',
    summary: 'Draft cover letters and messages from the offer and your profile, then edit them your way. Claude first.',
    bullets: ['Cover letters', 'Messages to recruiters', 'You keep the final word'],
    icon: 'pen',
    plan: 'free',
    soon: true,
    order: 60,
  },
  {
    key: 'desktop-app',
    theme: 'everywhere',
    title: 'Desktop app for macOS',
    summary: 'The same account and data on your Mac, and the place where your searches run.',
    bullets: ['Same account as on the web', 'Your sessions stay on your Mac'],
    icon: 'apple',
    plan: 'free',
    order: 70,
  },
  {
    key: 'browser-extension',
    theme: 'everywhere',
    title: 'Browser extension',
    summary: 'Save an offer while you browse and fill application forms from your profile.',
    bullets: ['Application autofill', 'Save offers in one click'],
    icon: 'browser',
    plan: 'free',
    soon: true,
    order: 80,
  },
  {
    key: 'mobile-app',
    theme: 'everywhere',
    title: 'Mobile app',
    summary: 'Check an application or read your prep notes on the way to an interview. iOS first.',
    bullets: ['Same account and data', 'iOS first'],
    icon: 'mobile',
    plan: 'free',
    soon: true,
    order: 90,
  },
  {
    key: 'mailbox-calendar',
    theme: 'control',
    title: 'Mailbox and calendar',
    summary: 'Replies from companies update your applications, and interviews land in your calendar.',
    bullets: ['Reply tracking', 'Calendar sync'],
    icon: 'mail',
    plan: 'plus',
    soon: true,
    order: 100,
  },
  {
    key: 'privacy-controls',
    theme: 'control',
    title: 'Privacy controls',
    summary: 'Your data is never used to train AI. Export it or delete your account whenever you want.',
    bullets: ['No AI training on your data', 'Data export', 'Account deletion'],
    icon: 'lock',
    plan: 'free',
    soon: true,
    order: 110,
  },
];
