import type { PageContent, PageSlug } from '../types';

export const pages: Record<PageSlug, PageContent> = {
  home: {
    slug: 'home',
    seo: {
      title: 'applyspace - Your job search, finally in one space',
      description: 'Find the right job offers, track every application and prepare your interviews, all in one calm space. Free to start.',
    },
    eyebrow: 'For job seekers',
    heading: 'Every offer, application and interview. One calm space.',
    intro: 'Find the right offers, track every application and prepare your interviews, all in one space.',
    ctas: [
      { label: 'Get started free', href: '/login', kind: 'app' },
      { label: 'Download for macOS', href: '/download', kind: 'download' },
    ],
    note: 'Free to start. No card needed.',
    heroDemo: {
      key: 'board',
      label: 'Live demo of the Applications board: drag a card to another column, or use its menu to change its status.',
      caption: 'Applications, Board view. Try moving a card.',
    },
    sections: [
      {
        type: 'scatter',
        title: 'One application, five tools.',
        body: "The offer lives in a browser tab, the status in a spreadsheet, the recruiter's name in your email, the interview in your calendar and your notes somewhere else. applyspace keeps all of it together, for every application.",
        fragments: [
          { kind: 'tab', label: 'Browser tab', text: 'Product Designer - 34 tabs' },
          { kind: 'sheet', label: 'Spreadsheet', text: 'applications_v7_final.xlsx' },
          { kind: 'note', label: 'Notes', text: 'Interview Tues? ask about remote' },
          { kind: 'email', label: 'Email', text: 'Re: your application' },
          { kind: 'calendar', label: 'Calendar', text: 'Call with recruiter' },
        ],
      },
      {
        type: 'spotlight',
        anchor: 'job-offers',
        eyebrow: 'Job offers',
        title: 'The offers that fit, in one list.',
        body: 'Describe what you look for once: title, city, contract, remote. Run the search from the desktop app and new offers land in your account, without duplicates.',
        bullets: ['Search profiles you can reuse', 'One list, no duplicates', 'Save an offer to your applications in one click'],
        link: { label: 'See how search works', href: '/product#offers-search' },
        demoSide: 'right',
        demo: {
          key: 'search',
          label: 'Live demo of the job offers search: type in the field, pick a contract, a city or remote, and save offers.',
          caption: "Search profile 'Product Designer, Paris'. Try the filters.",
        },
      },
      {
        type: 'views',
        anchor: 'applications',
        eyebrow: 'Applications',
        title: 'See every application your way.',
        intro: 'Four views on the same data. Move a card, and the table, timeline and map follow.',
        label: 'Live demo of the Applications hub with Board, Table, Timeline and Map layouts',
        views: [
          { key: 'board', label: 'Board', caption: 'Drag applications from one status to the next.' },
          { key: 'table', label: 'Table', caption: 'Sort by company, status or date.' },
          { key: 'timeline', label: 'Timeline', caption: "See what happened, and what's next." },
          { key: 'map', label: 'Map', caption: 'See where your applications are, and how far.' },
        ],
      },
      {
        type: 'spotlight',
        anchor: 'interviews',
        eyebrow: 'Interviews',
        title: 'Walk into every interview prepared.',
        body: "Each interview keeps its date, the people you meet, your notes and your questions, linked to the application. After the call, write down how it went while it's fresh.",
        bullets: ['Every round on one timeline', 'Notes and questions per interview', 'Linked to the offer and the company'],
        demoSide: 'left',
        demo: {
          key: 'interviews',
          label: 'Live demo of an interview process: select a round to see its date, people, prep notes and questions.',
          caption: 'An interview process, round by round. Click through it.',
        },
      },
      {
        type: 'flow',
        anchor: 'profile',
        eyebrow: 'Profile',
        title: 'Your profile, filled from your resume.',
        body: 'Drop a PDF or DOCX, or your LinkedIn export. Your experience, education, languages and skills are filled in for you to review and edit.',
        steps: [{ label: 'Import your resume' }, { label: 'Fields are read' }, { label: 'Review your profile' }],
        demo: {
          key: 'profile',
          label: 'Live demo of the resume import: press Import a resume to fill the profile.',
          caption: 'Resume to profile. Press Import a resume.',
        },
      },
      {
        type: 'steps',
        title: 'From first search to signed offer.',
        items: [
          { title: 'Import your resume', text: 'Your profile is ready in a minute.' },
          { title: 'Search for offers', text: 'Run your search profiles from the desktop app.' },
          { title: 'Track your applications', text: 'Every status, document and contact together.' },
          { title: 'Prepare your interviews', text: 'Notes, questions and next steps per round.' },
        ],
      },
      {
        type: 'download',
        eyebrow: 'Desktop app',
        title: 'Searches run from the desktop app.',
        body: 'The macOS app runs your search profiles with your own sessions on the job sites you use. New offers are saved to your account, so you find them on the web too.',
        bullets: ['Same account on the web and on your Mac', 'Your sessions stay on your Mac', 'Offers saved to your account, without duplicates'],
      },
      {
        type: 'trust',
        title: 'Your job search stays yours.',
        intro: "Your current employer doesn't need to know. Neither does anyone else.",
        items: [
          { icon: 'lock', title: 'Private to your account', text: 'Your offers, applications and notes are scoped to your account. Nobody else can read them.' },
          { icon: 'analytics', title: 'Analytics only if you agree', text: 'Usage analytics are off until you opt in, and you can turn them off any time.' },
          { icon: 'ai', title: 'Your AI, your account', text: "AI features run on your own AI accounts. We don't resell your data or train AI on it." },
          { icon: 'leave', title: 'Leave whenever you want', text: 'Export your data or delete your account from Settings.' },
        ],
      },
      {
        type: 'plans',
        title: 'Free to start. More room when you need it.',
        intro: 'Start on Free. Move to Plus or Max when your search picks up, and come back whenever you want.',
        variant: 'compact',
        footnote: 'Every plan includes search, all application views, interviews and resume import.',
      },
      {
        type: 'facts',
        eyebrow: 'Product facts',
        title: 'What you get, in plain words.',
        items: [
          { value: 'Web and Mac', label: 'One account everywhere', text: 'The same applications in the browser and in the macOS app.' },
          { value: 'In sync', label: 'Every view, same data', text: 'Board, table, timeline and map show the same applications.' },
          { value: 'Resume in', label: 'Profile filled for you', text: 'A PDF, a DOCX or your LinkedIn export fills your profile for review.' },
          { value: 'Opt-in', label: 'Analytics if you agree', text: 'Nothing is measured until you say yes.' },
        ],
      },
      {
        type: 'faq',
        title: 'Questions, answered.',
        link: { label: 'Pricing questions', href: '/pricing' },
        items: [
          { question: 'Is applyspace free?', answer: 'Yes, you can start for free, with no card. Plus and Max give you more room when your search picks up; the Pricing page has the details.' },
          { question: 'Why do I need the desktop app?', answer: 'Searches run from the desktop app, using your own sessions on the job sites you use. Results are saved to your account and visible on the web too.' },
          { question: 'Who can see my data?', answer: 'Only you. Your data is scoped to your account.' },
          { question: 'How does the AI work?', answer: 'AI features use your own AI account, so you stay in control of what is sent and to whom.' },
          { question: 'Can I import my resume?', answer: 'Yes: PDF, DOCX or your LinkedIn export.' },
          { question: 'Can I leave with my data?', answer: 'Yes. Export your data or delete your account from Settings, whenever you want.' },
        ],
      },
      {
        type: 'cta',
        title: 'Give your job search one space.',
        text: 'Free to start. No card needed.',
        cta: { label: 'Get started free', href: '/login', kind: 'app' },
        secondary: { label: 'Download for macOS', href: '/download', kind: 'download' },
        preview: 'board',
      },
    ],
  },
  product: {
    slug: 'product',
    seo: {
      title: 'Product: search, track and prepare in one app',
      description: 'Job offers search, an applications hub with board, table, timeline and map, interview tracking and a resume-powered profile.',
    },
    heading: 'Everything for your job search, in one app',
    intro: 'From the first offer to the final interview, every space works on the same data.',
    sections: [
      { type: 'features' },
      {
        type: 'cta',
        title: 'See it with your own search',
        text: 'Free to start. Import your resume and set up in minutes.',
        cta: { label: 'Start for free', href: '/login', kind: 'app' },
      },
    ],
  },
  pricing: {
    slug: 'pricing',
    seo: {
      title: 'Pricing: Free, Plus and Max',
      description: 'Start free with 15 applications. Plus raises the cap to 99 and Max has no limits.',
    },
    heading: 'Start free, upgrade when you need more',
    intro: 'Pick the room you need for your search. Change plan at any time.',
    sections: [
      {
        type: 'plans',
        variant: 'full',
      },
      {
        type: 'faq',
        title: 'Frequently asked questions',
        items: [
          { question: 'Is applyspace free?', answer: 'Yes. The Free plan includes application tracking, interview preparation and the core tools, with a cap of 15 applications, one search profile and one interview template.' },
          { question: 'What counts as an application?', answer: 'Every application you save counts toward your cap. Free allows 15, Plus 99 and Max has no limit.' },
          { question: 'Can I change plan later?', answer: 'Yes. You can upgrade when you need more room and return to Free at any time.' },
          { question: 'What happens to my data if I go back to Free?', answer: 'Your data is kept. You return to the Free possibilities, which means a lower cap and fewer search profiles.' },
          { question: 'Does applyspace pay for AI?', answer: 'No. AI features run on your own AI accounts (Claude, OpenAI or Gemini), so you stay in control of the cost and of your documents.' },
          { question: 'Where is my data stored?', answer: 'Everything is stored in the cloud, in a hosted database with per-user access rules, so you find your search on any device.' },
        ],
      },
      {
        type: 'cta',
        title: 'Start on the Free plan',
        text: 'No card needed.',
        cta: { label: 'Start for free', href: '/login', kind: 'app' },
      },
    ],
  },
  resources: {
    slug: 'resources',
    seo: {
      title: 'Resources: guides for a calmer job search',
      description: 'Practical guides on searching, tracking applications and preparing interviews.',
    },
    heading: 'Resources',
    intro: 'Practical guides on searching, tracking and interviewing.',
    sections: [],
  },
};
